import { corsair } from "@/src/server/corsair";
import { toNextJsHandler } from "corsair";

// Export the GET and POST handlers generated by Corsair's Next.js adapter
export const { GET, POST } = toNextJsHandler(corsair, {
  basePath: "/api/corsair",
});
